# Generated by Django 4.1.7 on 2023-06-21 21:08

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(
                default=backend.models.generate_unique_code, max_length=8, unique=True
            ),
        ),
    ]
